name: CI Pipeline

on:
  push:
    paths:
      - 'app/**'
      - 'tests/**'
      - 'run.py'
  pull_request:
    paths:
      - 'app/**'
      - 'tests/**'
      - 'run.py'
  workflow_dispatch:   # Manual trigger

jobs:
  ci:
    runs-on: ubuntu-latest   # Use your local self-hosted runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Build API
        run: make build

      - name: Run tests
        run: make test

      - name: Run linting
        run: make lint

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Docker build
        run: make docker-build DOCKER_IMAGE=${{ secrets.DOCKER_IMAGE }}

      - name: Docker push
        run: make docker-push DOCKER_IMAGE=${{ secrets.DOCKER_IMAGE }}
